#!/usr/bin/env bash
# Setup task breakdown workflow for Collab
# Generated by Sekkei CLI

set -e  # Exit on error

FEATURE_NAME="$1"
if [ -z "$FEATURE_NAME" ]; then
  # Try to detect feature from current directory
  CURRENT_DIR=$(basename "$PWD")
  if [[ "$CURRENT_DIR" =~ ^[0-9]{3}-.+ ]]; then
    FEATURE_NAME="$CURRENT_DIR"
  else
    echo "Usage: $0 <feature-name>"
    echo "Example: $0 003-user-authentication"
    echo "Or run from within a feature directory"
    exit 1
  fi
fi

FEATURE_DIR="sekkei-specs/${FEATURE_NAME}"

if [ ! -d "$FEATURE_DIR" ]; then
  echo "Error: Feature directory not found: $FEATURE_DIR"
  exit 1
fi

if [ ! -f "$FEATURE_DIR/plan.md" ]; then
  echo "Error: plan.md not found in $FEATURE_DIR"
  echo "Run /sekkei.plan first to create the implementation plan"
  exit 1
fi

echo "Creating task breakdown for: ${FEATURE_NAME}"

# Copy tasks template
cp .sekkei/templates/task-template.md "$FEATURE_DIR/tasks.md"

# Create task directories
mkdir -p "$FEATURE_DIR/tasks/planned"
mkdir -p "$FEATURE_DIR/tasks/doing"
mkdir -p "$FEATURE_DIR/tasks/for_review"
mkdir -p "$FEATURE_DIR/tasks/done"

echo "✓ Task breakdown created at ${FEATURE_DIR}/tasks.md"
echo "✓ Task directories created (planned/doing/for_review/done)"
echo ""
echo "Next steps:"
echo "  1. Edit ${FEATURE_DIR}/tasks.md with work packages and subtasks"
echo "  2. Create work package prompts in ${FEATURE_DIR}/tasks/planned/"
echo "  3. Run /sekkei.implement when ready to start implementation"
