#!/usr/bin/env bash
# Setup planning workflow for Collab
# Generated by Sekkei CLI

set -e  # Exit on error

FEATURE_NAME="$1"
if [ -z "$FEATURE_NAME" ]; then
  # Try to detect feature from current directory
  CURRENT_DIR=$(basename "$PWD")
  if [[ "$CURRENT_DIR" =~ ^[0-9]{3}-.+ ]]; then
    FEATURE_NAME="$CURRENT_DIR"
  else
    echo "Usage: $0 <feature-name>"
    echo "Example: $0 003-user-authentication"
    echo "Or run from within a feature directory"
    exit 1
  fi
fi

FEATURE_DIR="sekkei-specs/${FEATURE_NAME}"

if [ ! -d "$FEATURE_DIR" ]; then
  echo "Error: Feature directory not found: $FEATURE_DIR"
  echo "Run /sekkei.specify first to create the specification"
  exit 1
fi

if [ ! -f "$FEATURE_DIR/spec.md" ]; then
  echo "Error: spec.md not found in $FEATURE_DIR"
  exit 1
fi

echo "Creating implementation plan for: ${FEATURE_NAME}"

# Copy plan template
cp .sekkei/templates/plan-template.md "$FEATURE_DIR/plan.md"

# Create contracts directory
mkdir -p "$FEATURE_DIR/contracts"

echo "✓ Implementation plan created at ${FEATURE_DIR}/plan.md"
echo "✓ Contracts directory created at ${FEATURE_DIR}/contracts/"
echo ""
echo "Next steps:"
echo "  1. Edit ${FEATURE_DIR}/plan.md with architecture and implementation details"
echo "  2. Create API contracts in ${FEATURE_DIR}/contracts/ if needed"
echo "  3. Run /sekkei.tasks when ready to break down into work packages"
