#!/usr/bin/env bash
# Implementation workflow for Collab
# Generated by Sekkei CLI

set -e  # Exit on error

FEATURE_NAME="$1"
if [ -z "$FEATURE_NAME" ]; then
  # Try to detect feature from current directory
  CURRENT_DIR=$(basename "$PWD")
  if [[ "$CURRENT_DIR" =~ ^[0-9]{3}-.+ ]]; then
    FEATURE_NAME="$CURRENT_DIR"
  else
    echo "Usage: $0 <feature-name>"
    echo "Example: $0 003-user-authentication"
    echo "Or run from within a feature directory"
    exit 1
  fi
fi

FEATURE_DIR="sekkei-specs/${FEATURE_NAME}"

if [ ! -d "$FEATURE_DIR" ]; then
  echo "Error: Feature directory not found: $FEATURE_DIR"
  exit 1
fi

if [ ! -f "$FEATURE_DIR/tasks.md" ]; then
  echo "Error: tasks.md not found in $FEATURE_DIR"
  echo "Run /sekkei.tasks first to create the task breakdown"
  exit 1
fi

echo "Starting implementation for: ${FEATURE_NAME}"
echo ""
echo "Implementation workflow:"
echo "  1. Work packages start in tasks/planned/"
echo "  2. Move to tasks/doing/ when active"
echo "  3. Move to tasks/for_review/ when complete"
echo "  4. After review, move to tasks/done/"
echo ""
echo "To move a work package:"
echo "  - From planned to doing: Start WP implementation"
echo "  - From doing to for_review: Complete WP implementation"
echo "  - From for_review to done: Pass review"
echo ""

# Count work packages
PLANNED_COUNT=$(find "$FEATURE_DIR/tasks/planned" -name "WP*.md" 2>/dev/null | wc -l)
DOING_COUNT=$(find "$FEATURE_DIR/tasks/doing" -name "WP*.md" 2>/dev/null | wc -l)
REVIEW_COUNT=$(find "$FEATURE_DIR/tasks/for_review" -name "WP*.md" 2>/dev/null | wc -l)
DONE_COUNT=$(find "$FEATURE_DIR/tasks/done" -name "WP*.md" 2>/dev/null | wc -l)

echo "Current status:"
echo "  Planned: $PLANNED_COUNT"
echo "  Doing: $DOING_COUNT"
echo "  For Review: $REVIEW_COUNT"
echo "  Done: $DONE_COUNT"
echo ""

if [ "$PLANNED_COUNT" -eq 0 ] && [ "$DOING_COUNT" -eq 0 ] && [ "$REVIEW_COUNT" -eq 0 ]; then
  if [ "$DONE_COUNT" -gt 0 ]; then
    echo "✓ All work packages complete!"
    echo "Run /sekkei.accept to validate and merge feature"
  else
    echo "⚠ No work packages found. Create work package prompts in tasks/planned/"
  fi
else
  echo "Next: Review work packages in ${FEATURE_DIR}/tasks/planned/"
  echo "Implement each work package following the prompt guidance"
fi
