#!/usr/bin/env bash
# Setup specification workflow for Collab
# Generated by Sekkei CLI

set -e  # Exit on error

FEATURE_NAME="$1"
if [ -z "$FEATURE_NAME" ]; then
  echo "Usage: $0 <feature-name>"
  echo "Example: $0 user-authentication"
  exit 1
fi

# Generate feature number (next available)
LAST_NUM=$(find sekkei-specs -maxdepth 1 -type d -name '[0-9]*' 2>/dev/null | sort -V | tail -1 | grep -oE '[0-9]+' || echo "0")
FEATURE_NUM=$(printf "%03d" $((LAST_NUM + 1)))
FEATURE_DIR="sekkei-specs/${FEATURE_NUM}-${FEATURE_NAME}"

echo "Creating feature spec: ${FEATURE_DIR}"

# Create feature directory
mkdir -p "$FEATURE_DIR"

# Copy spec template
cp .sekkei/templates/spec-template.md "$FEATURE_DIR/spec.md"

# Update spec with feature details
sed -i.bak "s/\[Feature Name\]/${FEATURE_NAME}/g" "$FEATURE_DIR/spec.md" && rm "$FEATURE_DIR/spec.md.bak"
sed -i.bak "s/\[###-feature-name\]/${FEATURE_NUM}-${FEATURE_NAME}/g" "$FEATURE_DIR/spec.md" && rm "$FEATURE_DIR/spec.md.bak"
sed -i.bak "s/\[YYYY-MM-DD\]/$(date +%Y-%m-%d)/g" "$FEATURE_DIR/spec.md" && rm "$FEATURE_DIR/spec.md.bak"

echo "✓ Specification created at ${FEATURE_DIR}/spec.md"
echo ""
echo "Next steps:"
echo "  1. Edit ${FEATURE_DIR}/spec.md with feature details"
echo "  2. Run /sekkei.plan when ready to create implementation plan"
echo "  3. Or run /sekkei.research if technical investigation needed"
