#!/usr/bin/env bash
# Setup research workflow for Collab
# Generated by Sekkei CLI

set -e  # Exit on error

FEATURE_NAME="$1"
if [ -z "$FEATURE_NAME" ]; then
  # Try to detect feature from current directory
  CURRENT_DIR=$(basename "$PWD")
  if [[ "$CURRENT_DIR" =~ ^[0-9]{3}-.+ ]]; then
    FEATURE_NAME="$CURRENT_DIR"
  else
    echo "Usage: $0 <feature-name>"
    echo "Example: $0 003-user-authentication"
    echo "Or run from within a feature directory"
    exit 1
  fi
fi

FEATURE_DIR="sekkei-specs/${FEATURE_NAME}"

if [ ! -d "$FEATURE_DIR" ]; then
  echo "Error: Feature directory not found: $FEATURE_DIR"
  exit 1
fi

if [ ! -f "$FEATURE_DIR/spec.md" ]; then
  echo "Error: spec.md not found in $FEATURE_DIR"
  exit 1
fi

echo "Setting up research for: ${FEATURE_NAME}"

# Copy research template
cp .sekkei/templates/research-template.md "$FEATURE_DIR/research.md"

# Create research directory
mkdir -p "$FEATURE_DIR/research"

# Create evidence tracking files
cat > "$FEATURE_DIR/research/evidence-log.csv" << EOF
id,date,source_id,finding,confidence,notes
EOF

cat > "$FEATURE_DIR/research/source-register.csv" << EOF
source_id,type,title,author,url,access_date,credibility
EOF

echo "✓ Research document created at ${FEATURE_DIR}/research.md"
echo "✓ Research directory created at ${FEATURE_DIR}/research/"
echo "✓ Evidence tracking files created"
echo ""
echo "Next steps:"
echo "  1. Document research questions in ${FEATURE_DIR}/research.md"
echo "  2. Track evidence in ${FEATURE_DIR}/research/evidence-log.csv"
echo "  3. Maintain sources in ${FEATURE_DIR}/research/source-register.csv"
echo "  4. Run /sekkei.plan when research conclusions are reached"
