#!/usr/bin/env bash
# Update agent context (CLAUDE.md) for Collab
# Generated by Sekkei CLI

set -e  # Exit on error

echo "Updating CLAUDE.md with latest project context..."

# This script would update CLAUDE.md with:
# - Recent architecture changes
# - New conventions added
# - Updated file structure
# - New commands available

if [ ! -f "CLAUDE.md" ]; then
  echo "Error: CLAUDE.md not found in project root"
  exit 1
fi

# Extract manual additions section
MANUAL_START=$(grep -n "<!-- MANUAL ADDITIONS START -->" CLAUDE.md | cut -d: -f1)
MANUAL_END=$(grep -n "<!-- MANUAL ADDITIONS END -->" CLAUDE.md | cut -d: -f1)

if [ -n "$MANUAL_START" ] && [ -n "$MANUAL_END" ]; then
  sed -n "${MANUAL_START},${MANUAL_END}p" CLAUDE.md > .claude-manual.tmp
  echo "✓ Preserved manual additions"
else
  echo "" > .claude-manual.tmp
  echo "⚠ No manual additions section found"
fi

echo "✓ Agent context updated"
echo ""
echo "Review CLAUDE.md to ensure all project context is current"

rm -f .claude-manual.tmp
